# Generated by Django 5.1.6 on 2025-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("CLIENT", "Client"),
                    ("MASTER", "Master"),
                    ("MANAGER", "Manager"),
                    ("SUPERADMIN", "Superadmin"),
                ],
                default="CLIENT",
                max_length=255,
                null=True,
            ),
        ),
    ]
