# Generated by Django 5.1.6 on 2025-03-02 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "ico", "webp"]
                    )
                ],
            ),
        ),
    ]
