# Generated by Django 5.1.6 on 2025-03-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0002_alter_industryuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industryuser",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="industryuser_industry",
                to="industry.industry",
            ),
        ),
    ]
