# Generated by Django 5.1.6 on 2025-03-02 15:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the announcement", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the announcement", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the announcement",
                        null=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Geographic location coordinates",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Physical address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "industry",
                    models.JSONField(
                        blank=True,
                        help_text="Industry related information in JSON format",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title",
                        max_length=300,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="announcement_name_idx"),
                    models.Index(fields=["title"], name="announcement_title_idx"),
                ],
            },
        ),
    ]
